sudo: required
services:
  - docker
env:
  global:
    # Setting envionment variables from git commit as SHA
    - SHA=$(git rev-parse HEAD)
    # Configures google CLI to disable all user prompts
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d  
  # Download and install google cloud SDK
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  # Install kubectl inside of Travis environment
  - gcloud components update kubectl
  # gcloud authentication (IAM)
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-docker-kubernetes-293213
  - gcloud config set compute/zone asia-southeast1-a
  - gcloud container clusters get-credentials multi-cluster
  # Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Build the test image + tag
  - docker build -t limyeehan/react-test -f ./client/Dockerfile.dev ./client

script:
  # Run tests 
  - docker run -e CI=true limyeehan/react-test npm test


deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
